### ISSUE TITLE
FFmpeg filter support?

### ISSUE THREAD

**Issue by meltah** [oddity-ai/video-rs#29]
Is there any way to use FFmpeg filters (such as those done using the `-vf` flag on the ffmpeg CLI) with this crate? If not, is there a way to interop with `ffmpeg-next` to do this?

**Comment by gerwin3** [comment]
That is unfortunately not in the scope of this library. ffmpeg-next does have it I think. You can pull raw frames and interop with ffmpeg-next, that would work most likely (I haven't tried).
