### ISSUE TITLE
[Feature Request] Hope to support generating videos sent through http streaming instead of just saving them locally.

### ISSUE THREAD

**Issue by HiWayne** [oddity-ai/video-rs#30]
I'm doing a simple remote screen sharing. The current solution is to capture the screen frame by frame and combine them into a video and send it to the client via http.

However, this lib can only save video locally, and it lacks the function of adding frame to http video stream (such as `add_frame_to_stream`).

**Comment by gerwin3** [comment]
Depending on exactly what you're trying to do this can actually achieved by using:
* `Decoder::decode_raw` to get a raw decoded frame, which can then be transcoded into whatever you want, OR
* `Decoder::decode` (with `ndarray`) to get the actual RGB data and send it over HTTP (if that is what you want).

Alternatively, if you don't need to decode it before sending it you can `Reader::read`
