### ISSUE TITLE
Audio support

### ISSUE THREAD

**Issue by snowway** [oddity-ai/video-rs#44]
This project is great and  the API is very user friendly, but when I converted the original video, I found that the audio information was lost. can anyone help me?

**Comment by kaixoo** [comment]
hi, luckily i am having a similar use case. you have to use ffmpeg4-sys to decode the audio separately. in the midterm, it would be wise to contribute to video-rs to have this functionality. check this blog post: https://subvisual.com/blog/posts/real-time-video-processing-with-rust-ffmpeg-opencv/

**Comment by kaixoo** [comment]
Hi @snowway would you like to collaborate on an audio encoder? I have an 8 day deadline.

**Comment by gerwin3** [comment]
Unfortunately, audio is not supported right now. Any contributions would be greatly appreciated though.

**Comment by kaixoo** [comment]
Could easily contribute if I get indication on where the change should be made, etc. at least for basic formats like mp3. Do you have Discord or matrix?

**Comment by gerwin3** [comment]
Probably the easiest way would be to add an AudioDecoder interface next to the existing decoder.
