### ISSUE TITLE
Video end behavior regression

### ISSUE THREAD

**Issue by FlashOnFire** [oddity-ai/video-rs#53]
Hi
I'm running into an issue with the recent versions of video-rs
I recently upgraded my project from video-rs 0.8..1 to the latest version and it now produces an Ffmpeg backend error EOF when reaching the end of a video instead of a regular readexhausted (or the new decodeexhausted).

I bisected this, it works fine on 0.9.0 and stops working on 0.10.0 and above

This simple minimal code is enough to reproduce the bug :
```Rust
use std::path::PathBuf;
use video_rs::{Decoder, Error, Location};

fn main() {
    let source = Location::File(PathBuf::from("test.mp4"));
    let mut decoder = Decoder::new(source).expect("Failed to create decoder");

    let mut i = 0;
    loop {
        match decoder.decode() {
            Ok(_) => {
                println!("Frame : {i}");
                i += 1;
            }
            Err(err) => match err {
                Error::ReadExhausted => {
                    decoder.seek_to_start().unwrap();
                    i = 0;
                    println!("restart");
                }
                _ => panic!("Error while decoding video frames : {:?}", err),
            },
        };
    }
}
```

Am i missing something ?

**Comment by gerwin3** [comment]
Thanks for reporting! Should be fixed in 0.10.2 :)
